version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 #--settings=blog.settings.dev
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env/.dev
    depends_on:
      - db

  db:
    image: postgres:13.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dockershop


volumes:
  postgres_data: